### ISSUE TITLE
Order by "sorting" does not work

### ISSUE THREAD

**Issue by saschaluebeck** [tieupmedia/HwtTypo3HwtAddress#6]
When I pick some single addesses and choose "sorting" for the order, the sorting is ignored in the frontend.

**Comment by tieupmedia** [comment]
Oh, I'm sorry that you have trouble with it! I did a quick test with TYPO3 8.x and it works for me like intended so far. 

But I got a suspicion. Where did you expect the sorting - on the storage page in the record list or the selection list inside the plugin? It's the first one, that's implemented (until now?).

**Comment by saschaluebeck** [comment]
I thought it is the sorting of the selection inside the plugin. I think that is the only place where it makes sense. I can sort the records directly in the plugin. I got several pages where at every page a diffent sorting is needed.

So, one Page need:

Person B
Person A
Person D

while another page needs:

Person A
Person B
Person D

So a unique sorting for every plugin is needed.

Typo3 is at 9.5.6, hwt_address is at 0.2.0
Thanks for your support!

**Comment by tieupmedia** [comment]
Okay, so this is a missing feature here. I agree, that it will be a useful one and an integration should be possible without massive work. I think I can realise that within the next days.

**Comment by saschaluebeck** [comment]
That would be great! Appreciate your work here really much! :)
Thanks!

**Comment by tieupmedia** [comment]
Thank you!

Beside the bugfix and maintenance releases yesterday, I prepared a feature branch [feature-sortby-plugin](/tieupmedia/HwtTypo3HwtAddress/tree/feature-sortby-plugin) on top of them, which adds a new sorting option. Do this match your needs?

I wanted to keep the old sorting option, because it enables the editors to select the addresses in a random order and display them in always the same order of the record list inside the storage page(s).

If you can review it with positive result, I would merge this into the next release.


Beside the sorting topic your description sounds like the "display related to page" feature maybe interessting for you to simplify the editor's work. This option was a bit hidden, but please see [Documentation/FeatureDisplayRelatedToPage.md](/tieupmedia/HwtTypo3HwtAddress/blob/master/Documentation/FeatureDisplayRelatedToPage.md) for further information. ~This one doesn't sorting at all for now, but I plan to improve it, too.~ In the feature branch this is improved to handle sorting by address fields and relation order, too.

**Comment by saschaluebeck** [comment]
The sorting now works great. This is the way we used older address extensions before and this feature comes right in time. Thanks a lot for you fast support here!

The "Display records related to the current page" sounds very interesting. Good to know this feature, thanks! I only wish it also would use the order of the relation field. And if you could setup the realation to inherited the relations of parents, that would be great. Often a special team is used for a part of the pagetree. That would make it even easier instead of add the address ressources to all pages over and over again.

**Comment by tieupmedia** [comment]
Perfect, so I will merge it into the next release.

If you use "Display records related to the current page" in your feature branch with the pre-configured TS, it uses (should use) the order of the relation field by default. The plugin will be adjusted soon.

The inheritance is a good idea! I will check, what's needed here to realise it.

**Comment by tieupmedia** [comment]
See 16d858f (and previous)

**Comment by tieupmedia** [comment]
Resolved with release 0.2.2

Inheritance for "display related to page" feature isn't done yet, cause I don't know anyone who really want's to use it for now. Major use cases maybe otherwise resolved with one plugin and the CE "insert record".
